require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2

# Offense count: 1
Metrics/AbcSize:
  Max: 17

# Offense count: 3
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 80

# Offense count: 2
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/sequel_password.rb'

# Offense count: 3
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 103

# Offense count: 7
# Configuration parameters: AggregateFailuresByDefault.
RSpec/MultipleExpectations:
  Max: 3
